apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: K8S_NAMESPACE_VALUE
  labels:
    component: httpd
    role: demo-svc
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
  selector:
    component: httpd